SQL:
  MySQL: false
  host: localhost
  port: 3306
  user: user
  pass: pass
  database: database
configuration:
  start-time: 120
  min-players: 5
  money-on-win: 15
messages:
  welcome:
  - '&f» Você está no &6SkyWars&f / Online aqui: &a{0}'
  - '&f» Para abrir a loja use: &9/loja'
  - '&f» Para voltar ao lobby principal: &9/spawn'
  game-start:
    message: 
    - ''
    - '&3[SkyWars] &bIniciando a rodada!!'
    - '&3[PRÊMIO] &bPremio deste minigame: &a{0} &bcoins!'
    - ''
  kill: '&e{0} &bfoi eliminado por &e{1}&b.'
  kill-void: '&c{0} morreu sozinho!'
  streak:
    double-kill: '&e{0} &bfez um &6&lDOUBLE-KILL &bem &e{1}&b!'
    triple-kill: '&e{0} &bfez um &6&lTRIPLE-KILL &bem &e{1}&b!'
    quadra-kill: '&e{0} &bfez um &6&lQUADRA-KILL &bem &e{1}&b!'
    penta-kill: '&e{0} &bfez um &6&lPENTA-KILL &bem &e{1}&b!'
  lose: '&c&lVOCÊ PERDEU A PARTIDA :('
  win:
    you: '&2Você ganhou: {0} coin(s)%n%&6&lVOCÊ VENCEU A PARTIDA!'
  starting:
    with-players: '&bIniciando a rodada em: &a{0} &bsegundo(s)!'
    without-players: '&bFaltam &c{0} &bjogador(es) para começar!'