SQL:
  host: localhost
  port: 3306
  user: root
  pass: D!Ak^qad2xfq
  database: minigames
  tags-table: nte_groups
  
groups:
    default-group: Membro
  
blocked-cmds:
- plugins
- pl
- op
- spartan
- bukkit:plugins
- bukkit:pl
- mv
- system
- pex
- permissionex
- plugman
- npc
- citizens
- holographicdisplays
- hd
- vault
- fawe
- idisguise
- nte
- nametagedit