SQL:
  MySQL: false
  host: localhost
  port: 3306
  user: user
  pass: pass
  database: database
configuration:
  start-time: 300
  min-players: 5
  money-first: 15
  money-second: 10
  money-three: 5
temas:
  Animais:
  - 'Galinha'
  - 'Lobo'
  - 'Porco'
  - 'Vaca'
  - 'Abelha'
  - 'Leão'
  Escola:
  - 'Borracha'
  - 'Mochila'
  - 'Quadro Negro'
  - 'Professor'
  - 'Caderno'
  - 'Aluno'
  - 'Calculadora'
  Objetos:
  - 'Âncora'
  - 'Anel'
  - 'Coroa'
  - 'Troféu'
  - 'Boneca'
  - 'Capacete'
  - 'Cata-vento'
  - 'Dinamite'
  - 'Espada'
  - 'Geladeira'
  - 'Garrafa'
messages:
  welcome:
  - '&f» Você está no &6Minigame&f / Online aqui: &a{0}'
  - '&f» Para abrir a loja use: &9/loja'
  - '&f» Para voltar ao lobby principal: &9/spawn'
  boss: "&bTempo restante &e{0}&b!"
  game-start:
    message: 
    - ''
    - '&3[Minigame] &bIniciando a rodada!!'
    - '&3[PRÊMIO] &bPremio deste minigame: &a{0} &bcoins!'
    - ''
  
  lose: '&c&lVOCÊ PERDEU A PARTIDA :('
  shop:
    vip: '&6{0} &bÉ VIP e pegou um item grátis na loja!'
    normal: '&6{0} &bcomprou um item por &6{1} &bcoin(s) na loja!'
  win:
    you: '&2Você ganhou: {0} coin(s)%n%&6&lVOCÊ VENCEU A PARTIDA!'
  starting:
    with-players: '&bIniciando a rodada em: &a{0} &bsegundo(s)!'
    without-players: '&bFaltam &c{0} &bjogadores ou &e{1} &bsegundos para começar!'