SQL:
  MySQL: false
  host: localhost
  port: 3306
  user: user
  pass: pass
  database: database
configuration:
  start-time: 300
  min-players: 5
  money-on-win: 15
messages:
  death: '&c{0} morreu!'
  welcome:
  - '&f» Você está no &6Frog&f / Online aqui: &a{count-players}'
  - '&f» Para abrir a loja use: &9/loja'
  - '&f» Para voltar ao lobby principal: &9/spawn'
  game-start:
    message: 
    - ''
    - '&3[Frog] &bIniciando a rodada!!'
    - '&3[PRÊMIO] &bPremio deste minigame: &a{0} &bcoins!'
    - ''
    - '&3[Frog] A lã preta irá desaparecer em 30 segundo!!'
    - ''
  lose: '&c&lVOCÊ PERDEU A PARTIDA :('
  win:
    you: '&2Você ganhou: {0} coin(s)%n%&6&lVOCÊ VENCEU A PARTIDA!'
    other: '&c{0} venceu a partida!'
  starting:
    with-players: '&bIniciando a rodada em: &a{0} &bsegundo(s)!'
    without-players: '&bFaltam &c{0} &bjogadores ou &e{1} &bsegundos para começar!'